version: 2
jobs:
    build:
        machine: true

        steps:
            - checkout

            - run:
                name: Prepare docker
                when: always
                command: docker run --privileged -v ${PWD}:/opt/Viola-linux -itd --name arch archlinux/base:latest

            - run:
                name: Prevent symbolic link error
                when: always
                command: docker exec -it arch mkdir /run/shm

            - run:
                name: Add arcolinux mirrorlist
                when: always
                command: |
                    docker exec -it arch /bin/bash -c \
                    "{
                        echo 'Server = https://master.seedhost.eu/arcolinux/\$repo/\$arch'
                        echo 'Server = https://arcolinux.github.io/\$repo/\$arch'
                        echo 'Server = https://driesdubois.be/\$repo/\$arch'
                    } > /etc/pacman.d/arcolinux-mirrorlist"

            - run:
                name: Update pacman repositories
                when: always
                command: docker exec -it arch pacman -Sy

            - run:
                name: Install build dependencies
                when: always
                command: docker exec -it arch pacman -S --noconfirm git wget archiso polkit file

            - run:
                name: Build iso
                when: always
                no_output_timeout: 1h
                command: docker exec -it arch /bin/bash -c "cd /opt/Viola-linux/ && bash build-iso.sh"

            - run:
                name: Copy artifacts from container to host
                when: always
                command: sudo docker cp `docker ps -aq -f "name=arch"`:/root/ViolaLinux-Out ./ViolaLinux-Out

            - run:
                name: Examine artifacts
                when: always
                command: ls -lh ./ViolaLinux-Out

            - store_artifacts:
                path: ./ViolaLinux-Out
